version: 2

run:
  timeout: 5m

linters:
  enable:
    # Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters available in this version
    - bodyclose
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - unconvert
    - unparam
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  funlen:
    lines: 150
    statements: 100
  
  gocognit:
    min-complexity: 100
  
  goconst:
    min-len: 2
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  
  gocyclo:
    min-complexity: 15
  
  lll:
    line-length: 120
  
  nakedret:
    max-func-lines: 30
