name: Build and Release Binary

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: |
          go build -o ./cmd/app-git-copy ./cmd

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-git-copy-linux-amd64
          path: cmd/app-git-copy
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: cmd/app-git-copy
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
