name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update-go-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Run tests
        run: |
          go test -v ./test/...

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet go.mod go.sum; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "chore: update Go dependencies"
          title: "🔄 Update Go Dependencies"
          body: |
            ## Automated Dependency Update

            This PR updates Go dependencies to their latest versions.

            ### Changes
            - Updated Go modules to latest versions
            - Ran `go mod tidy` to clean up dependencies

            ### Testing
            - [x] All tests pass
            - [x] Dependencies are compatible

            ### Review Notes
            Please review the changes and ensure:
            - No breaking changes in updated dependencies
            - All tests continue to pass
            - Security vulnerabilities are addressed

            ---

            🤖 This PR was created automatically by the dependency update workflow.
          branch: chore/update-dependencies
          branch-suffix: timestamp
          delete-branch: true
          labels: |
            dependencies
            automated
            chore
          reviewers: pal-paul

  update-github-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Update GitHub Actions
        uses: nicknovitski/action-updates@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet .github/workflows/; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "chore: update GitHub Actions to latest versions"
          title: "🔄 Update GitHub Actions"
          body: |
            ## Automated GitHub Actions Update

            This PR updates GitHub Actions to their latest versions.

            ### Changes
            - Updated action versions in workflow files
            - Ensures latest features and security fixes

            ### Testing
            - [x] Workflow files are valid
            - [x] No breaking changes detected

            ### Review Notes
            Please review the changes and ensure:
            - Workflow compatibility is mastertained
            - No deprecated actions are introduced
            - Security best practices are followed

            ---

            🤖 This PR was created automatically by the dependency update workflow.
          branch: chore/update-github-actions
          branch-suffix: timestamp
          delete-branch: true
          labels: |
            dependencies
            automated
            github-actions
            chore
          reviewers: pal-paul

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run security audit
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Run nancy (dependency vulnerability check)
        run: |
          go list -json -deps ./... | docker run --rm -i sonatypecommunity/nancy:latest sleuth

      - name: Create issue for vulnerabilities
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Vulnerabilities Detected',
              body: `## Security Alert
              
              Security vulnerabilities have been detected during the automated security audit.
              
              ### Action Required
              - [ ] Review the workflow logs for details
              - [ ] Update vulnerable dependencies
              - [ ] Run security audit locally to verify fixes
              
              ### Workflow Run
              [View logs](${context.payload.repository.html_url}/actions/runs/${context.runId})
              
              ---
              
              🤖 This issue was created automatically by the security audit workflow.`,
              labels: ['security', 'vulnerability', 'automated']
            });
